apiVersion: v1
kind: Pod
metadata:
  name: nginx-multi-container-pod
  namespace: roboshop
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 81
  - image: almalinux
    name: almalinux-sidecar
    command:  ["sleep", "10"]
