apiVersion: v1
kind: Pod
metadata:
  name: nginxv1
  namespace: roboshop
spec:
  containers:
    - image: nginx:1.14.2
      imagePullPolicy: Always
      name: nginx
      ports:
      - containerPort: 81