---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: roboshop
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 500m
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxv1
  namespace: roboshop
spec:
  containers:
    - image: nginx:1.14.2
      imagePullPolicy: Always
      name: nginx
      ports:
      - containerPort: 81