apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
  namespace: roboshop
spec:
  containers:
    - image: nginx
      name: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 85
        initialDelaySeconds: 3
        periodSeconds: 5