apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 87
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"