apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  namespace: roboshop
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 81
