apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  namespace: roboshop
  labels:
    name: nginx
spec:
  containers:
  - name: env-pod
    image: nginx
    env:
      - name: course
        value: docker
      - name: trainer
        value: kumar
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 82
