apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  namespace: roboshop
  labels:
    name: nginx
spec:
  containers:
  - name: env-pod
    image: nginx
    env:
      - name: course
        value: docker
      - name: trainer
        value: kumar
      - name: duration
        value: 30hrs
      - name: DB_HOST
        value: ab.domain.com
      - name: username
        value: kumar        
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 88
