# apiVersion: v1
# kind: Pod
# metadata:
#   name: config-pod
#   namespace: roboshop
# spec:
#   containers:
#   - name: nconfig-pod
#     image: nginx
#     env:
#     - name: course
#       valueFrom:
#         configMapKeyRef:
#           name: k8s-config
#           key: course-name
#     - name: duration
#       valueFrom:
#         configMapKeyRef:
#           name: k8s-config
#           key: course-duration
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 89
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
spec:
  containers:
  - name: nconfig-pod
    image: nginx
    envFrom:
      - configMapRef:
          name: k8s-config    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 89