apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
spec:
  containers:
  - name: nginx-config-pod
    image: nginx
    env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: k8s-config
            key: course_name
      - name: trainer
        value: kumar
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: k8s-config
            key: course_duration
    ports:
      - containerPort: 89
