apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 90
    env:
      - name: username
        valueFrom:
          secretKeyRef:
            name: roboshop-secrets 
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: roboshop-secrets
            key: password