apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kube-cluster
  region: ap-south-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1 #cluster node group name
  spot: true
  ssh:
    publicKeyName: sasi_mumbai
    