apiVersion: v1
kind: Pod
metadata:
  name: web-app-nginx
  labels:
    server: web-app-nginx
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 91
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-nginx-service
spec:
  selector:
    server: web-app-nginx
  ports:
  - protocol: TCP
    port: 91
    targetPort: 92
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    purpose: debug
spec:
  containers:
  - name: almalinux
    image: almalinux
    command: ["sleep","1000000"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"